services:
  app:
    build: .
    ports:
      - "3000:3000"
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    security_opt:
      - "apparmor:unconfined"
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    tmpfs:
      - /run:rw,noexec,nosuid,size=65536k
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
